from bs4 import BeautifulSoup

# Your HTML content
html_content = """
<select name="category" id="category"><option value="all">All Industries</option>
<option value="atm-businesses">ATM Businesses</option>
<option value="atv-snowmobile-and-jetski-dealers">ATV, Snowmobile and Jetski Dealers</option>
<option value="accountancy-practices">Accountancy Practices</option>
<option value="accounting">Accounting</option>
<option value="accounting-and-tax-practices">Accounting and Tax Practices</option>
<option value="adult-shops">Adult Shops</option>
<option value="advertising-businesses">Advertising Businesses</option>
<option value="advertising-and-marketing-services">Advertising and Marketing Services</option>
<option value="agricultural-supply-businesses">Agricultural Supply Businesses</option>
<option value="agriculture-businesses">Agriculture Businesses</option>
<option value="air-conditioning-businesses">Air Conditioning Businesses</option>
<option value="air-transport-businesses">Air Transport Businesses</option>
<option value="all-non-classifiable-establishments">All Non-Classifiable Establishments</option>
<option value="alternative-health-businesses">Alternative Health Businesses</option>
<option value="amazon-stores-fba-and-fbm">Amazon Stores (FBA &amp; FBM)</option>
<option value="ambulance-and-emt-services">Ambulance and EMT Services</option>
<option value="ambulatory-health-care-services">Ambulatory Health Care Services</option>
<option value="american-restaurants">American Restaurants</option>
<option value="amusement-parks-and-arcades">Amusement Parks And Arcades</option>
<option value="antique-and-art-shops">Antique And Art Shops</option>
<option value="appliance-repair">Appliance Repair</option>
<option value="aquatic-and-marine-businesses">Aquatic And Marine Businesses</option>
<option value="architect-practices">Architect Practices</option>
<option value="architecture-interior-design-landscape-design">Architecture, Interior Design, Landscape Design</option>
<option value="art-galleries">Art Galleries</option>
<option value="art-galleries-and-museums">Art Galleries And Museums</option>
<option value="arts-entertainment-and-recreation">Arts, Entertainment and Recreation</option>
<option value="asian-restaurants">Asian Restaurants</option>
<option value="assisted-living-facilities-care-homes-senior-housing">Assisted Living Facilities, Care Homes, Senior Housing</option>
<option value="assisted-living-and-nursing-homes">Assisted Living and Nursing Homes</option>
<option value="auto-body-shops">Auto Body Shops</option>
<option value="auto-parts-stores">Auto Parts Stores</option>
<option value="auto-parts-and-accessories">Auto Parts and Accessories</option>
<option value="auto-repair-businesses">Auto Repair Businesses</option>
<option value="auto-repair-shops-garages">Auto Repair Shops, Garages</option>
<option value="auto-repair-and-service-shops">Auto Repair and Service Shops</option>
<option value="automobile-and-motorcycle-dealers">Automobile and Motorcycle Dealers</option>
<option value="automotive-and-boat-businesses">Automotive and Boat Businesses</option>
<option value="aviation-businesses">Aviation Businesses</option>
<option value="aviation-services">Aviation Services</option>
<option value="bagel-shops">Bagel Shops</option>
<option value="bait-and-tackle-stores">Bait and Tackle Stores</option>
<option value="bakeries">Bakeries</option>
<option value="bakeries-and-bake-shops">Bakeries and Bake Shops</option>
<option value="bakers-and-confectioners">Bakers And Confectioners</option>
<option value="banking-and-loan-businesses">Banking and Loan Businesses</option>
<option value="banquet-halls">Banquet Halls</option>
<option value="bargain-stores">Bargain Stores</option>
<option value="bars">Bars</option>
<option value="bars-pubs-and-taverns">Bars, Pubs and Taverns</option>
<option value="bars-taverns-pubs-lounges">Bars, Taverns, Pubs, Lounges</option>
<option value="bathroom-related-businesses">Bathroom Related Businesses</option>
<option value="beauty-parlors-barbershops-hair-salons-hairdressers">Beauty Parlors, Barbershops, Hair Salons, Hairdressers</option>
<option value="beauty-and-personal-care-businesses">Beauty and Personal Care Businesses</option>
<option value="bed-and-breakfasts">Bed and Breakfasts</option>
<option value="beverage-distributors">Beverage Distributors</option>
<option value="bicycle-shops">Bicycle Shops</option>
<option value="bike-shops">Bike Shops</option>
<option value="bistros">Bistros</option>
<option value="boarding-kennels">Boarding Kennels</option>
<option value="boat-related-businesses">Boat Related Businesses</option>
<option value="book-shops">Book Shops</option>
<option value="bowling-clubs">Bowling Clubs</option>
<option value="bread-routes">Bread Routes</option>
<option value="breweries">Breweries</option>
<option value="bridal-shops">Bridal Shops</option>
<option value="building-maintenance-businesses">Building Maintenance Businesses</option>
<option value="building-material-and-hardware-stores">Building Material and Hardware Stores</option>
<option value="building-services-businesses">Building Services Businesses</option>
<option value="building-and-construction-businesses">Building and Construction Businesses</option>
<option value="bus-companies">Bus Companies</option>
<option value="business-brokerages">Business Brokerages</option>
<option value="business-services">Business Services</option>
<option value="butchers">Butchers</option>
<option value="butchers-meat-markets">Butchers, Meat Markets</option>
<option value="cafe-bars">Cafe Bars</option>
<option value="cafes">Cafes</option>
<option value="call-centers-answering-services-telemarketing">Call Centers, Answering Services, Telemarketing</option>
<option value="cannabis-businesses">Cannabis Businesses</option>
<option value="cannabis-stores">Cannabis Stores</option>
<option value="car-dealerships">Car Dealerships</option>
<option value="car-hire-businesses">Car Hire Businesses</option>
<option value="car-rental">Car Rental</option>
<option value="car-wash">Car Wash</option>
<option value="car-wash-and-valet-businesses">Car Wash And Valet Businesses</option>
<option value="car-washes">Car Washes</option>
<option value="card-and-gift-shops">Card And Gift Shops</option>
<option value="card-and-gift-shops1">Card and Gift Shops</option>
<option value="care-homes">Care Homes</option>
<option value="carpenters-and-joiners">Carpenters And Joiners</option>
<option value="carpentry-and-joinery">Carpentry and Joinery</option>
<option value="carpet-and-flooring-businesses1">Carpet And Flooring Businesses</option>
<option value="carpet-cleaning-equipment-businesses">Carpet Cleaning Equipment Businesses</option>
<option value="carpet-and-flooring-businesses">Carpet and Flooring Businesses</option>
<option value="catering-businesses">Catering Businesses</option>
<option value="catering-companies">Catering Companies</option>
<option value="catering-services">Catering Services</option>
<option value="cell-phone-and-computer-repair-and-service-businesses">Cell Phone and Computer Repair and Service Businesses</option>
<option value="chauffeur-businesses">Chauffeur Businesses</option>
<option value="check-cashing-businesses">Check Cashing Businesses</option>
<option value="check-cashing-payday-loans-pawn-shops">Check Cashing, Payday Loans, Pawn Shops</option>
<option value="chemical-businesses">Chemical Businesses</option>
<option value="chemical-and-related-product-manufacturers">Chemical and Related Product Manufacturers</option>
<option value="chemicals-and-chemical-products">Chemicals and Chemical Products</option>
<option value="child-care-centers">Child Care Centers</option>
<option value="child-care-nurseries">Child Care Nurseries</option>
<option value="children-s-play-businesses">Children S Play Businesses</option>
<option value="childrens-wear-shops">Childrens Wear Shops</option>
<option value="chinese-restaurants">Chinese Restaurants</option>
<option value="chiropractic-practices">Chiropractic Practices</option>
<option value="chiropractor-businesses">Chiropractor Businesses</option>
<option value="civil-engineering-businesses">Civil Engineering Businesses</option>
<option value="cleaning">Cleaning</option>
<option value="cleaning-services">Cleaning Services</option>
<option value="clothing-and-footwear-manufacturers">Clothing And Footwear Manufacturers</option>
<option value="clothing-businesses">Clothing Businesses</option>
<option value="clothing-wholesalers">Clothing Wholesalers</option>
<option value="clothing-and-accessory-stores">Clothing and Accessory Stores</option>
<option value="clothing-and-clothing-accessories">Clothing and Clothing Accessories</option>
<option value="clothing-and-fabric-manufacturers">Clothing and Fabric Manufacturers</option>
<option value="coffee-shops-and-cafes">Coffee Shops and Cafes</option>
<option value="coffee-shops-cafes-tea-rooms">Coffee Shops, Cafes, Tea Rooms</option>
<option value="commercial-banks-savings-banks">Commercial Banks, Savings Banks</option>
<option value="commercial-cleaning-businesses">Commercial Cleaning Businesses</option>
<option value="commercial-laundry-businesses">Commercial Laundry Businesses</option>
<option value="commercial-vehicle-dealerships">Commercial Vehicle Dealerships</option>
<option value="commercial-vehicle-hire-businesses">Commercial Vehicle Hire Businesses</option>
<option value="communication-and-media-businesses">Communication and Media Businesses</option>
<option value="computer-stores">Computer Stores</option>
<option value="computer-training-businesses">Computer Training Businesses</option>
<option value="concrete-businesses">Concrete Businesses</option>
<option value="concrete-and-cement-contractors">Concrete and Cement Contractors</option>
<option value="construction">Construction</option>
<option value="construction-businesses">Construction Businesses</option>
<option value="construction-professional-firms">Construction Professional Firms</option>
<option value="construction-supply-businesses">Construction Supply Businesses</option>
<option value="consultancy-businesses">Consultancy Businesses</option>
<option value="convenience-stores">Convenience Stores</option>
<option value="convenience-stores-c-stores">Convenience Stores, C-Stores</option>
<option value="corporate-training-businesses">Corporate Training Businesses</option>
<option value="cosmetic-medical-and-med-spa-businesses">Cosmetic Medical &amp; Med Spa Businesses</option>
<option value="cosmetic-stores">Cosmetic Stores</option>
<option value="counseling-services">Counseling Services</option>
<option value="couriers-messengers-despatch-riders">Couriers, Messengers, Despatch Riders</option>
<option value="craft-and-hobby-businesses">Craft And Hobby Businesses</option>
<option value="credit-and-finance-companies">Credit And Finance Companies</option>
<option value="curtain-and-blinds-businesses">Curtain And Blinds Businesses</option>
<option value="cutting-and-machining-machine-shops">Cutting and Machining, Machine Shops</option>
<option value="dance-studios">Dance Studios</option>
<option value="dance-pilates-and-yoga-studios">Dance, Pilates and Yoga Studios</option>
<option value="day-care-and-child-care-centers">Day Care and Child Care Centers</option>
<option value="decorating-businesses">Decorating Businesses</option>
<option value="delicatessens">Delicatessens</option>
<option value="delis-and-sandwich-shops">Delis and Sandwich Shops</option>
<option value="dental-laboratories">Dental Laboratories</option>
<option value="dental-practices">Dental Practices</option>
<option value="dental-practices-clinics">Dental Practices, Clinics</option>
<option value="design-agencies">Design Agencies</option>
<option value="diners">Diners</option>
<option value="distilleries">Distilleries</option>
<option value="distribution-businesses">Distribution Businesses</option>
<option value="diy-related-businesses">Diy Related Businesses</option>
<option value="dog-daycare-and-boarding-businesses">Dog Daycare and Boarding Businesses</option>
<option value="dollar-stores">Dollar Stores</option>
<option value="domain-name-businesses">Domain Name Businesses</option>
<option value="domestic-cleaning-businesses">Domestic Cleaning Businesses</option>
<option value="driving-schools">Driving Schools</option>
<option value="drug-stores-and-pharmacies">Drug Stores And Pharmacies</option>
<option value="dry-cleaners">Dry Cleaners</option>
<option value="dry-cleaning-laundry-services-laundromats">Dry Cleaning, Laundry Services, Laundromats</option>
<option value="e-commerce-businesses">E Commerce Businesses</option>
<option value="e-commerce">E-Commerce</option>
<option value="e-learning">E-Learning</option>
<option value="ecommerce">Ecommerce</option>
<option value="education">Education</option>
<option value="education-businesses">Education Businesses</option>
<option value="education-and-child-related-businesses">Education and Child Related Businesses</option>
<option value="electric-utilities">Electric Utilities</option>
<option value="electric-water-gas-and-sewer-services">Electric, Water,  Gas and Sewer Services</option>
<option value="electrical-appliance-manufacturers">Electrical Appliance Manufacturers</option>
<option value="electrical-appliance-retailers">Electrical Appliance Retailers</option>
<option value="electrical-contractors">Electrical Contractors</option>
<option value="electrical-equipment-appliances-and-components">Electrical Equipment, Appliances and Components</option>
<option value="electrical-services-businesses">Electrical Services Businesses</option>
<option value="electrical-and-mechanical-contracting-businesses">Electrical and Mechanical Contracting Businesses</option>
<option value="electricians-and-electrical-repair-businesses">Electricians And Electrical Repair Businesses</option>
<option value="electronic-and-electrical-equipment-manufacturers">Electronic and Electrical Equipment Manufacturers</option>
<option value="electronics-and-appliance-stores">Electronics and Appliance Stores</option>
<option value="elementary-and-secondary-schools">Elementary and Secondary Schools</option>
<option value="embroidery-services">Embroidery Services</option>
<option value="employee-training-and-motivation">Employee Training and Motivation</option>
<option value="employment-staffing-recruitment-temporary-help">Employment, Staffing, Recruitment, Temporary Help</option>
<option value="energy-related-businesses">Energy Related Businesses</option>
<option value="energy-and-petroleum-production-businesses">Energy and Petroleum Production Businesses</option>
<option value="engineering-businesses">Engineering Businesses</option>
<option value="engineering-consultancies">Engineering Consultancies</option>
<option value="engineering-manufacturing-businesses">Engineering Manufacturing Businesses</option>
<option value="engineering-and-surveying">Engineering and Surveying</option>
<option value="entertainment-agencies">Entertainment Agencies</option>
<option value="entertainment-and-fun-businesses">Entertainment And Fun Businesses</option>
<option value="entertainment-and-recreation-businesses">Entertainment and Recreation Businesses</option>
<option value="environmental-related-businesses">Environmental Related Businesses</option>
<option value="equipment-rental-and-dealers">Equipment Rental and Dealers</option>
<option value="equipment-rental-and-maintenance">Equipment Rental and Maintenance</option>
<option value="european-restaurants">European Restaurants</option>
<option value="event-planners">Event Planners</option>
<option value="event-planning-businesses">Event Planning Businesses</option>
<option value="events-businesses">Events Businesses</option>
<option value="excavating-contractors">Excavating Contractors</option>
<option value="fabrication-businesses">Fabrication Businesses</option>
<option value="facilities-management-businesses">Facilities Management Businesses</option>
<option value="farms">Farms</option>
<option value="fast-food-restaurants">Fast Food Restaurants</option>
<option value="fedex-routes">FedEx Routes</option>
<option value="fencing-businesses">Fencing Businesses</option>
<option value="finance-companies">Finance Companies</option>
<option value="finance-and-insurance">Finance and Insurance</option>
<option value="financial-businesses">Financial Businesses</option>
<option value="financial-related-businesses">Financial Related Businesses</option>
<option value="financial-services-businesses">Financial Services Businesses</option>
<option value="fine-dining-restaurants">Fine Dining Restaurants</option>
<option value="fireplace-and-stove-businesses">Fireplace And Stove Businesses</option>
<option value="fishing-and-related-businesses">Fishing And Related Businesses</option>
<option value="fishing-hunting-and-trapping">Fishing, Hunting and Trapping</option>
<option value="fitout-businesses">Fitout Businesses</option>
<option value="flight-schools">Flight Schools</option>
<option value="flooring-contractors">Flooring Contractors</option>
<option value="flooring-service-businesses">Flooring Service Businesses</option>
<option value="flooring-and-tile-stores">Flooring and Tile Stores</option>
<option value="florists">Florists</option>
<option value="florists-and-flower-shops">Florists and Flower Shops</option>
<option value="food-and-drink-distributors">Food And Drink Distributors</option>
<option value="food-and-drink-wholesalers">Food And Drink Wholesalers</option>
<option value="food-businesses">Food Businesses</option>
<option value="food-distributors">Food Distributors</option>
<option value="food-manufacturers">Food Manufacturers</option>
<option value="food-resale-franchises">Food Resale Franchises</option>
<option value="food-trucks">Food Trucks</option>
<option value="food-vending-businesses">Food Vending Businesses</option>
<option value="food-and-related-product-manufacturers">Food and Related Product Manufacturers</option>
<option value="framing-businesses">Framing Businesses</option>
<option value="franchise-resales">Franchise Resales</option>
<option value="fuel-oil-and-propane-dealers">Fuel Oil and Propane Dealers</option>
<option value="funeral-businesses">Funeral Businesses</option>
<option value="funeral-homes">Funeral Homes</option>
<option value="furniture-businesses">Furniture Businesses</option>
<option value="furniture-manufacturers">Furniture Manufacturers</option>
<option value="furniture-manufacturing-businesses">Furniture Manufacturing Businesses</option>
<option value="furniture-stores">Furniture Stores</option>
<option value="furniture-and-fixtures-manufacturers">Furniture and Fixtures Manufacturers</option>
<option value="furniture-and-furnishings-stores">Furniture and Furnishings Stores</option>
<option value="furniture-and-related-products">Furniture and Related Products</option>
<option value="garden-centers">Garden Centers</option>
<option value="garden-centres">Garden Centres</option>
<option value="gardening-businesses">Gardening Businesses</option>
<option value="gas-petrol-service-stations">Gas Petrol Service Stations</option>
<option value="gas-stations">Gas Stations</option>
<option value="gas-stations-truck-stops-petrol-stations">Gas Stations, Truck Stops, Petrol Stations</option>
<option value="general-contractors-builders-housebuilders">General Contractors, Builders, Housebuilders</option>
<option value="general-retail-businesses">General Retail Businesses</option>
<option value="general-services-businesses">General Services Businesses</option>
<option value="glass-contractors-glaziers">Glass Contractors, Glaziers</option>
<option value="glass-products-manufacturers">Glass Products Manufacturers</option>
<option value="glass-repair">Glass Repair</option>
<option value="glass-stone-and-concrete-manufacturers">Glass, Stone and Concrete Manufacturers</option>
<option value="glaziers">Glaziers</option>
<option value="golf-and-related-businesses">Golf And Related Businesses</option>
<option value="golf-courses-and-service-businesses">Golf Courses and Service Businesses</option>
<option value="graphic-design">Graphic Design</option>
<option value="greek-restaurant">Greek Restaurant</option>
<option value="greek-restaurants">Greek Restaurants</option>
<option value="greenhouses">Greenhouses</option>
<option value="greenhouses-and-nurseries">Greenhouses and Nurseries</option>
<option value="grocers-fruit-and-veg-markets">Grocers Fruit And Veg Markets</option>
<option value="grocers-fruit-and-vegetable-stores">Grocers, Fruit &amp; Vegetable Stores</option>
<option value="grocery-stores-and-supermarkets">Grocery Stores and Supermarkets</option>
<option value="guest-houses-and-bed-and-breakfast-businesses">Guest Houses And Bed And Breakfast Businesses</option>
<option value="gyms-and-fitness-centers">Gyms and Fitness Centers</option>
<option value="hvac">HVAC</option>
<option value="hair-and-beauty-salons">Hair And Beauty Salons</option>
<option value="hair-salons-and-barber-shops">Hair Salons and Barber Shops</option>
<option value="hardware-stores">Hardware Stores</option>
<option value="health-and-beauty-businesses">Health And Beauty Businesses</option>
<option value="health-and-beauty-supply-businesses">Health And Beauty Supply Businesses</option>
<option value="health-and-fitness-clubs">Health And Fitness Clubs</option>
<option value="health-and-safety-businesses">Health And Safety Businesses</option>
<option value="health-care">Health Care</option>
<option value="health-care-businesses">Health Care Businesses</option>
<option value="health-care-and-fitness-businesses">Health Care and Fitness Businesses</option>
<option value="health-clubs-fitness-centres-spas">Health Clubs, Fitness Centres, Spas</option>
<option value="health-food-shops">Health Food Shops</option>
<option value="health-food-and-nutrition-businesses">Health Food and Nutrition Businesses</option>
<option value="health-and-beauty-products">Health and Beauty Products</option>
<option value="heating-businesses">Heating Businesses</option>
<option value="heating-ventilating-cooling-mechanical-contractors">Heating, Ventilating, Cooling, Mechanical Contractors</option>
<option value="heavy-construction">Heavy Construction</option>
<option value="heavy-construction-businesses">Heavy Construction Businesses</option>
<option value="heavy-machinery-businesses">Heavy Machinery Businesses</option>
<option value="hire-businesses">Hire Businesses</option>
<option value="hobby-and-crafts-stores">Hobby and Crafts Stores</option>
<option value="holiday-businesses">Holiday Businesses</option>
<option value="home-accessories-businesses">Home Accessories Businesses</option>
<option value="home-and-garden-businesses">Home And Garden Businesses</option>
<option value="home-furnishings">Home Furnishings</option>
<option value="home-health-care-businesses">Home Health Care Businesses</option>
<option value="home-health-care-services">Home Health Care Services</option>
<option value="home-inspection-services">Home Inspection Services</option>
<option value="hookah-bars">Hookah Bars</option>
<option value="hotels">Hotels</option>
<option value="house-and-garden-businesses">House And Garden Businesses</option>
<option value="house-and-garden-products-manufacturing-businesses">House And Garden Products Manufacturing Businesses</option>
<option value="housebuilding-businesses">Housebuilding Businesses</option>
<option value="it-and-software-service-businesses">IT and Software Service Businesses</option>
<option value="ice-cream-and-frozen-yogurt-shops">Ice Cream and Frozen Yogurt Shops</option>
<option value="ice-cream-yogurt-and-smoothie-shops">Ice Cream, Yogurt, and Smoothie Shops</option>
<option value="import-and-export-businesses">Import And Export Businesses</option>
<option value="importers-and-exporters">Importers and Exporters</option>
<option value="indian-restaurants">Indian Restaurants</option>
<option value="industrial-businesses">Industrial Businesses</option>
<option value="industrial-cleaning-businesses">Industrial Cleaning Businesses</option>
<option value="industrial-supplies">Industrial Supplies</option>
<option value="industrial-warehouses-distribution-businesses">Industrial Warehouses Distribution Businesses</option>
<option value="industrial-and-commercial-machinery-manufacturers">Industrial and Commercial Machinery Manufacturers</option>
<option value="information-technology-businesses">Information Technology Businesses</option>
<option value="insurance-agencies">Insurance Agencies</option>
<option value="insurance-agencies-brokers">Insurance Agencies, Brokers</option>
<option value="insurance-related-businesses">Insurance Related Businesses</option>
<option value="interior-design-businesses">Interior Design Businesses</option>
<option value="internet-businesses">Internet Businesses</option>
<option value="internet-and-online-businesses">Internet and Online Businesses</option>
<option value="investment-opportunities">Investment Opportunities</option>
<option value="it-businesses">It Businesses</option>
<option value="it-consultancy-businesses">It Consultancy Businesses</option>
<option value="it-maintenance-businesses">It Maintenance Businesses</option>
<option value="it-manufacturing-businesses">It Manufacturing Businesses</option>
<option value="it-network-businesses">It Network Businesses</option>
<option value="it-retail-businesses">It Retail Businesses</option>
<option value="it-software-businesses">It Software Businesses</option>
<option value="it-telecommunications-businesses">It Telecommunications Businesses</option>
<option value="italian-restaurants">Italian Restaurants</option>
<option value="janitorial-and-cleaning-services">Janitorial and Cleaning Services</option>
<option value="jewellers">Jewellers</option>
<option value="jewelry-stores">Jewelry Stores</option>
<option value="juice-bars">Juice Bars</option>
<option value="junk-and-salvage-yards">Junk and Salvage Yards</option>
<option value="kitchen-and-bedroom-manufacturers">Kitchen And Bedroom Manufacturers</option>
<option value="kitchen-related-businesses">Kitchen Related Businesses</option>
<option value="ladies-wear-shops">Ladies Wear Shops</option>
<option value="land">Land</option>
<option value="landscape-gardening-businesses">Landscape Gardening Businesses</option>
<option value="landscaping">Landscaping</option>
<option value="landscaping-contractors">Landscaping Contractors</option>
<option value="landscaping-lawn-care-and-tree-services">Landscaping, Lawn Care and Tree Services</option>
<option value="laundries">Laundries</option>
<option value="laundromats-and-coin-laundry-businesses">Laundromats and Coin Laundry Businesses</option>
<option value="law-firms-barristers-solicitors-legal-services">Law Firms, Barristers, Solicitors, Legal Services</option>
<option value="lawyers-legal-firms">Lawyers Legal Firms</option>
<option value="leisure-businesses">Leisure Businesses</option>
<option value="leisure-resale-franchises">Leisure Resale Franchises</option>
<option value="limo-and-passenger-transportation-businesses">Limo and Passenger Transportation Businesses</option>
<option value="liquor-stores">Liquor Stores</option>
<option value="liquor-stores-and-off-licences">Liquor Stores And Off Licences</option>
<option value="liquor-stores-off-licences-wine-shops">Liquor Stores, Off-Licences, Wine Shops</option>
<option value="locksmiths">Locksmiths</option>
<option value="logistics-companies">Logistics Companies</option>
<option value="long-haul-trucking">Long Haul Trucking</option>
<option value="lumber-and-building-products">Lumber and Building Products</option>
<option value="lumber-and-wood-products-manufacturers">Lumber and Wood Products Manufacturers</option>
<option value="machine-shop">Machine Shop</option>
<option value="machine-shops-and-tool-manufacturers">Machine Shops and Tool  Manufacturers</option>
<option value="machinery-and-equipment">Machinery &amp; Equipment</option>
<option value="machinery-and-metal-businesses">Machinery And Metal Businesses</option>
<option value="machinery-repair-and-maintenance-businesses">Machinery Repair And Maintenance Businesses</option>
<option value="machinery-excluding-computers">Machinery, Excluding Computers</option>
<option value="magazine-publishing">Magazine Publishing</option>
<option value="magazines-and-newspapers">Magazines and Newspapers</option>
<option value="mail-order-businesses">Mail Order Businesses</option>
<option value="main-contractors">Main Contractors</option>
<option value="maintenance-businesses">Maintenance Businesses</option>
<option value="management-consultancies">Management Consultancies</option>
<option value="management-consulting-consultancies">Management Consulting, Consultancies</option>
<option value="management-rights-opportunities">Management Rights Opportunities</option>
<option value="manufacturing">Manufacturing</option>
<option value="manufacturing-businesses">Manufacturing Businesses</option>
<option value="marinas">Marinas</option>
<option value="marinas-and-fishing-businesses">Marinas and Fishing Businesses</option>
<option value="marketing-businesses">Marketing Businesses</option>
<option value="marketing-and-advertising-businesses">Marketing and Advertising Businesses</option>
<option value="masonry-contractors">Masonry Contractors</option>
<option value="massage-businesses">Massage Businesses</option>
<option value="meat-distributors">Meat Distributors</option>
<option value="mechanical-services-businesses">Mechanical Services Businesses</option>
<option value="media-businesses">Media Businesses</option>
<option value="medical-billing-businesses">Medical Billing Businesses</option>
<option value="medical-device-and-product-manufacturers">Medical Device and Product Manufacturers</option>
<option value="medical-equipment">Medical Equipment</option>
<option value="medical-practices">Medical Practices</option>
<option value="medical-practices-clinics-therapy-centres">Medical Practices, Clinics, Therapy Centres</option>
<option value="medical-products-distributors">Medical Products Distributors</option>
<option value="medical-products-manufacturing-businesses">Medical Products Manufacturing Businesses</option>
<option value="medical-staffing">Medical Staffing</option>
<option value="medical-supply-businesses">Medical Supply Businesses</option>
<option value="medical-transportation-businesses">Medical Transportation Businesses</option>
<option value="mens-wear-shops">Mens Wear Shops</option>
<option value="metal-fabrication">Metal Fabrication</option>
<option value="metal-product-manufacturers">Metal Product Manufacturers</option>
<option value="metal-products-manufacturers">Metal Products Manufacturers</option>
<option value="mexican-restaurants">Mexican Restaurants</option>
<option value="middle-eastern-restaurants">Middle Eastern Restaurants</option>
<option value="mining-businesses">Mining Businesses</option>
<option value="miscellaneous-restaurant-and-bars">Miscellaneous Restaurant and Bars</option>
<option value="motels">Motels</option>
<option value="motor-cycle-businesses">Motor Cycle Businesses</option>
<option value="motorcycle-businesses">Motorcycle Businesses</option>
<option value="moving-companies">Moving Companies</option>
<option value="moving-and-shipping-businesses">Moving and Shipping Businesses</option>
<option value="music-stores">Music Stores</option>
<option value="nail-salons">Nail Salons</option>
<option value="new-and-used-car-sale-businesses">New And Used Car Sale Businesses</option>
<option value="nightclubs">Nightclubs</option>
<option value="nightclubs-and-theaters">Nightclubs and Theaters</option>
<option value="nursery-and-garden-centers">Nursery and Garden Centers</option>
<option value="nursing-services">Nursing Services</option>
<option value="office-furniture-businesses">Office Furniture Businesses</option>
<option value="offices-and-business-centers">Offices And Business Centers</option>
<option value="oil-and-petrochemical-related-businesses">Oil And Petrochemical Related Businesses</option>
<option value="oil-and-gas-exploration">Oil and Gas Exploration</option>
<option value="online-and-technology-businesses">Online and Technology Businesses</option>
<option value="opticians-and-optical-stores">Opticians And Optical Stores</option>
<option value="optometrists">Optometrists</option>
<option value="other-agriculture">Other Agriculture</option>
<option value="other-arts-entertainment-and-recreation-businesses">Other Arts, Entertainment and Recreation Businesses</option>
<option value="other-business-services">Other Business Services</option>
<option value="other-construction">Other Construction</option>
<option value="other-food-distributors">Other Food Distributors</option>
<option value="other-food-and-grocery-stores">Other Food and Grocery Stores</option>
<option value="other-health-care">Other Health Care</option>
<option value="other-industries">Other Industries</option>
<option value="other-information-businesses">Other Information Businesses</option>
<option value="other-internet-and-online-businesses">Other Internet and Online Businesses</option>
<option value="other-manufacturing">Other Manufacturing</option>
<option value="other-metal-fabrication">Other Metal Fabrication</option>
<option value="other-personal-service-businesses">Other Personal Service Businesses</option>
<option value="other-real-estate">Other Real Estate</option>
<option value="other-restaurants">Other Restaurants</option>
<option value="other-retailing">Other Retailing</option>
<option value="other-transportation">Other Transportation</option>
<option value="other-trucking">Other Trucking</option>
<option value="other-wholesale-trade">Other Wholesale Trade</option>
<option value="outdoor-adventure-businesses">Outdoor Adventure Businesses</option>
<option value="pack-and-ship-services">Pack and Ship Services</option>
<option value="packaging-businesses">Packaging Businesses</option>
<option value="packaging-distributors">Packaging Distributors</option>
<option value="painting-businesses">Painting Businesses</option>
<option value="painting-contractors">Painting Contractors</option>
<option value="paper-manufacturers-and-printing-businesses">Paper Manufacturers and Printing Businesses</option>
<option value="paper-and-packaging">Paper and Packaging</option>
<option value="parking-lot-maintenance">Parking Lot Maintenance</option>
<option value="party-rental-and-supply-stores">Party Rental and Supply Stores</option>
<option value="party-stores">Party Stores</option>
<option value="paving-contractors">Paving Contractors</option>
<option value="pawn-shops">Pawn Shops</option>
<option value="personal-services">Personal Services</option>
<option value="pest-control">Pest control</option>
<option value="pet-businesses">Pet Businesses</option>
<option value="pet-grooming-businesses">Pet Grooming Businesses</option>
<option value="pet-grooming-and-boarding-kennels-catteries">Pet Grooming and Boarding, Kennels, Catteries</option>
<option value="pet-service-businesses">Pet Service Businesses</option>
<option value="pet-shops">Pet Shops</option>
<option value="pet-shops-and-supplies">Pet Shops and Supplies</option>
<option value="pet-stores-and-supply-businesses">Pet Stores and Supply Businesses</option>
<option value="pharmacies">Pharmacies</option>
<option value="pharmacies-drug-stores-chemists">Pharmacies, Drug Stores, Chemists</option>
<option value="photographic-service-businesses">Photographic Service Businesses</option>
<option value="photography-studios">Photography Studios</option>
<option value="physical-therapy-practices">Physical Therapy Practices</option>
<option value="pizza">Pizza</option>
<option value="pizza-restaurants">Pizza Restaurants</option>
<option value="plastic-fabrication-businesses">Plastic Fabrication Businesses</option>
<option value="plastics-and-rubber">Plastics and Rubber</option>
<option value="plumbing">Plumbing</option>
<option value="plumbing-businesses">Plumbing Businesses</option>
<option value="plumbing-contractors">Plumbing Contractors</option>
<option value="pool-service-and-maintenance">Pool Service and Maintenance</option>
<option value="postal-and-communication-businesses">Postal And Communication Businesses</option>
<option value="powder-coating-businesses">Powder Coating Businesses</option>
<option value="preschools">Preschools</option>
<option value="printing-and-typesetting-businesses">Printing And Typesetting Businesses</option>
<option value="printing-and-duplicating-services">Printing and Duplicating Services</option>
<option value="professional-service-businesses">Professional Service Businesses</option>
<option value="property-agencies">Property Agencies</option>
<option value="property-management">Property Management</option>
<option value="property-management-businesses">Property Management Businesses</option>
<option value="property-services">Property Services</option>
<option value="publishing-businesses">Publishing Businesses</option>
<option value="pubs">Pubs</option>
<option value="quick-lube-and-oil-change-services">Quick Lube and Oil Change Services</option>
<option value="rv-and-caravan-dealers">RV and Caravan Dealers</option>
<option value="real-estate">Real Estate</option>
<option value="real-estate-development-opportunities">Real Estate Development Opportunities</option>
<option value="recording-studios">Recording Studios</option>
<option value="recreation-businesses">Recreation Businesses</option>
<option value="recruitment-agencies">Recruitment Agencies</option>
<option value="recycling-businesses">Recycling Businesses</option>
<option value="removal-businesses">Removal Businesses</option>
<option value="repair-services">Repair Services</option>
<option value="residential-properties">Residential Properties</option>
<option value="resort-properties">Resort Properties</option>
<option value="resorts">Resorts</option>
<option value="restaurants">Restaurants</option>
<option value="restaurants-and-food-businesses">Restaurants and Food Businesses</option>
<option value="retail-businesses">Retail Businesses</option>
<option value="retail-resale-franchises">Retail Resale Franchises</option>
<option value="retail-shops-to-lease">Retail Shops To Lease</option>
<option value="road-haulage-and-freight-businesses">Road Haulage And Freight Businesses</option>
<option value="roofing-businesses">Roofing Businesses</option>
<option value="roofing-contractors">Roofing Contractors</option>
<option value="roofing-service-businesses">Roofing Service Businesses</option>
<option value="routes">Routes</option>
<option value="rubber-and-plastic-products-manufacturers">Rubber and Plastic Products Manufacturers</option>
<option value="rv-parks">Rv Parks</option>
<option value="saas-businesses">SaaS Businesses</option>
<option value="sales-businesses">Sales Businesses</option>
<option value="sandwich-shops-bagel-shops-sub-shops">Sandwich Shops, Bagel Shops, Sub Shops</option>
<option value="sawmills">Sawmills</option>
<option value="schools">Schools</option>
<option value="screen-printing-businesses">Screen Printing Businesses</option>
<option value="scuba-diving-businesses">Scuba Diving Businesses</option>
<option value="seafood-distributors">Seafood Distributors</option>
<option value="security-businesses">Security Businesses</option>
<option value="security-and-fire-alarm-services">Security and Fire Alarm Services</option>
<option value="self-storage">Self Storage</option>
<option value="self-storage-warehouses">Self Storage Warehouses</option>
<option value="service-businesses">Service Businesses</option>
<option value="service-resale-franchises">Service Resale Franchises</option>
<option value="services-businesses">Services Businesses</option>
<option value="sewer-services">Sewer Services</option>
<option value="shoe-stores">Shoe Stores</option>
<option value="short-haul-trucking">Short Haul Trucking</option>
<option value="sign-makers">Sign Makers</option>
<option value="sign-manufacturers-and-businesses">Sign Manufacturers and Businesses</option>
<option value="sign-shops">Sign Shops</option>
<option value="smoke-shops">Smoke Shops</option>
<option value="snack-bars">Snack Bars</option>
<option value="snack-distributors">Snack Distributors</option>
<option value="snooker-and-pool-centres">Snooker And Pool Centres</option>
<option value="social-services">Social Services</option>
<option value="soft-furnishing-businesses">Soft Furnishing Businesses</option>
<option value="software-companies">Software Companies</option>
<option value="software-and-app-companies">Software and App Companies</option>
<option value="solar-businesses">Solar Businesses</option>
<option value="spas">Spas</option>
<option value="specialist-food-retailers">Specialist Food Retailers</option>
<option value="specialist-subcontractors">Specialist Subcontractors</option>
<option value="speech-therapy-practices">Speech Therapy Practices</option>
<option value="sport-equipment-manufacturers">Sport Equipment Manufacturers</option>
<option value="sporting-goods-stores">Sporting Goods Stores</option>
<option value="sporting-goods-and-shooting-range-businesses">Sporting Goods and Shooting Range Businesses</option>
<option value="sports-centres">Sports Centres</option>
<option value="sports-shops">Sports Shops</option>
<option value="sports-teams">Sports Teams</option>
<option value="staffing-agencies">Staffing Agencies</option>
<option value="stationery-and-office-supply-businesses">Stationery And Office Supply Businesses</option>
<option value="stationery-and-office-supplies">Stationery and Office Supplies</option>
<option value="stone-clay-glass-and-concrete">Stone, Clay, Glass and Concrete</option>
<option value="storage-warehouse-businesses">Storage Warehouse Businesses</option>
<option value="strip-clubs">Strip Clubs</option>
<option value="strip-clubs-adult-clubs-gentlemens-clubs">Strip Clubs, Adult Clubs, Gentlemen's Clubs</option>
<option value="supermarkets">Supermarkets</option>
<option value="surveyors">Surveyors</option>
<option value="sushi-seafood-restaurants">Sushi Seafood Restaurants</option>
<option value="sushi-and-japanese-restaurants">Sushi and Japanese Restaurants</option>
<option value="swimming-pool-businesses">Swimming Pool Businesses</option>
<option value="tailors">Tailors</option>
<option value="tailors-tailoring">Tailors, Tailoring</option>
<option value="take-aways">Take Aways</option>
<option value="take-out-take-away">Take Out, Take Away</option>
<option value="talent-agencies">Talent Agencies</option>
<option value="tanning-salons">Tanning Salons</option>
<option value="taxi-businesses">Taxi Businesses</option>
<option value="taxi-limousine-car-hire-chauffeur-services">Taxi, Limousine, Car Hire, Chauffeur Services</option>
<option value="technical-service-businesses">Technical Service Businesses</option>
<option value="technology-and-media-businesses">Technology And Media Businesses</option>
<option value="textile-products-excluding-clothing">Textile Products, Excluding Clothing</option>
<option value="thai-restaurants">Thai Restaurants</option>
<option value="tire-businesses">Tire Businesses</option>
<option value="tire-dealers">Tire Dealers</option>
<option value="tobacco-shops-cigar-stores">Tobacco Shops, Cigar Stores</option>
<option value="tobacconists">Tobacconists</option>
<option value="tool-and-equipment-hire-businesses">Tool And Equipment Hire Businesses</option>
<option value="toolmakers-and-precision-businesses">Toolmakers And Precision Businesses</option>
<option value="towing-companies">Towing Companies</option>
<option value="toy-shops">Toy Shops</option>
<option value="toy-stores">Toy Stores</option>
<option value="trade-contractors">Trade Contractors</option>
<option value="transportation-businesses">Transportation Businesses</option>
<option value="transportation-related-manufacturing-businesses">Transportation Related Manufacturing Businesses</option>
<option value="transportation-and-storage-businesses">Transportation and Storage Businesses</option>
<option value="travel-businesses">Travel Businesses</option>
<option value="tree-farms-and-orchards">Tree Farms and Orchards</option>
<option value="truck-stops">Truck Stops</option>
<option value="trucking-companies">Trucking Companies</option>
<option value="trucking-companies-road-haulage">Trucking Companies, Road Haulage</option>
<option value="tutoring-services">Tutoring Services</option>
<option value="tv-and-radio-businesses">Tv And Radio Businesses</option>
<option value="tv-audio-video-and-photographic-businesses">Tv Audio Video And Photographic Businesses</option>
<option value="upholstery-and-carpet-cleaning">Upholstery and Carpet Cleaning</option>
<option value="vehicle-accessory-shops">Vehicle Accessory Shops</option>
<option value="vehicle-related-businesses">Vehicle Related Businesses</option>
<option value="vending">Vending</option>
<option value="vending-routes">Vending Routes</option>
<option value="veterinary-businesses">Veterinary Businesses</option>
<option value="veterinary-clinics">Veterinary Clinics</option>
<option value="video-game-stores">Video Game Stores</option>
<option value="vineyards-and-wineries">Vineyards and Wineries</option>
<option value="vocational-schools">Vocational Schools</option>
<option value="waste-management-and-recycling-businesses">Waste Management and Recycling Businesses</option>
<option value="waste-management-and-remediation-services">Waste Management and Remediation Services</option>
<option value="water-businesses-and-stores">Water Businesses and Stores</option>
<option value="water-utilities">Water Utilities</option>
<option value="watersports-rentals">Watersports Rentals</option>
<option value="web-design-and-development-businesses">Web Design And Development Businesses</option>
<option value="web-site-development">Web Site Development</option>
<option value="websites">Websites</option>
<option value="wedding-catering-businesses">Wedding Catering Businesses</option>
<option value="wedding-clothing-businesses">Wedding Clothing Businesses</option>
<option value="wedding-venues">Wedding Venues</option>
<option value="wholesale-and-distribution-businesses1">Wholesale And Distribution Businesses</option>
<option value="wholesale-businesses">Wholesale Businesses</option>
<option value="wholesale-and-distribution-businesses">Wholesale and Distribution Businesses</option>
<option value="wholesalers-and-distributors">Wholesalers and Distributors</option>
<option value="wine-bars">Wine Bars</option>
<option value="wineries">Wineries</option>
<option value="wood-products-manufacturing-businesses">Wood Products Manufacturing Businesses</option></select>
"""

# Parse the HTML content
soup = BeautifulSoup(html_content, 'html.parser')

# Find the select element by its id or name
select = soup.find('select', {'id': 'category'})

# Extract option text from the select element
option_names = [option.get_text() for option in select.find_all('option')]

# Print all option names
for name in option_names:
    print(name)
